# site settings
title: Forty
subtitle: by HTML5 UP
email: aida.perramon.m@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/EpinfantsCAT" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: A. Perramon Malavez
city: Barcelona

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

collections:
  plots:
    output: true
    permalink: /plots/:slug/

# social settings (key must match name of font awesome icon)
socials:
  GitHub: https://github.com/aida-pm
  LinkedIn: https://www.linkedin.com/in/aidaperramon/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
- scripts
- requirements.txt
- data
- "__pycache__"
- venv
