# site settings
title: EpinfantsCAT
email: aida.perramon.m@gmail.com
description: Pàgina web per veure com avancen les epidèmies de virus respiratoris a la població infantil de Catalunya.
baseurl: "/EpinfantsCAT" 
author: A. Perramon Malavez
city: Barcelona

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

collections:
  plots:
    output: true
    permalink: /plots/:slug/

# social settings 
socials:
  GitHub: https://github.com/aida-pm
  LinkedIn: https://www.linkedin.com/in/aidaperramon/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
- scripts
- requirements.txt
- data
- "__pycache__"
- venv
