# site settings
title: EpinfantsCAT
email: aida.perramon.m@gmail.com
description: Epidèmies de virus respiratoris en infants catalans
baseurl: "/EpinfantsCAT"
author: A. Perramon Malavez
city: Barcelona

# homepage tiles
tiles-source: pages 
tiles-count: 4

# social settings (key must match name of font awesome icon)
socials:
  GitHub: https://github.com/aida-pm
  LinkedIn: https://www.linkedin.com/in/aidaperramon/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
- scripts
- requirements.txt
- data
- "__pycache__"
- venv
